### ISSUE TITLE
Password is not checked

### ISSUE THREAD

**Issue by gellner** [UKCloud/openshift-heat#25]
Password requested during deploy.sh is not checked.

Indeed - can it maybe take it from the OS_PASSWORD env var?

**Comment by stevemul** [comment]
There's no guarantee you're deploying using the same user as gets passed in for integration. Having said that I think you can pass the password you want as a argument to the deploy.sh script so you could use something like ./deploy.sh $OS_PASSWORD if the password is correct?

**Comment by gellner** [comment]
Ha! I guess I could have actually checked the source of the script first... :)
