### ISSUE TITLE
Command fails when run by cloud-init - any commands added after will not be run

### ISSUE THREAD

**Issue by k8soneill** [UKCloud/openshift-heat#92]
https://github.com/UKCloud/openshift-heat/blob/b07608751013a8fc813685b7dd7a8051e76769fa/server_with_port.yaml#L81

**Comment by k8soneill** [comment]
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: + nmcli d connect eth1
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: Error: Device 'eth1' not found.
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: [CLOUDINIT] util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [10]
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: 2019-02-19 11:58:09,198 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [10]
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: [CLOUDINIT] util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [10]
                                                               Traceback (most recent call last):
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 617, in runparts
                                                                   subp(prefix + [exe_path], capture=False)
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1570, in subp
                                                                   cmd=args)
                                                               ProcessExecutionError: Unexpected error while running command.
                                                               Command: ['/var/lib/cloud/instance/scripts/part-001']
                                                               Exit code: 10
                                                               Reason: -
                                                               Stdout: ''
                                                               Stderr: ''
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: [CLOUDINIT] cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: [CLOUDINIT] util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: 2019-02-19 11:58:09,205 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: 2019-02-19 11:58:09,206 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Feb 19 11:58:09 haproxy-cp-0.koneill-sandbox cloud-init[5067]: [CLOUDINIT] util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
                                                               Traceback (most recent call last):
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 660, in _run_modules
                                                                   cc.run(run_name, mod.handle, func_args, freq=freq)
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 63, in run
                                                                   return self._runners.run(name, functor, args, freq, clear_on_fail)
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 197, in run
                                                                   results = functor(*args)
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
                                                                   util.runparts(runparts_path)
                                                                 File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 624, in runparts
                                                                   % (len(failed), len(attempted)))
                                                               RuntimeError: Runparts: 1 failures in 1 attempted commands

**Comment by stevemul** [comment]
Feel free to remove it, pretty sure its legacy from the time we were running a secondary network interface and cloud-init didn't ever configure it. Obviously we don't need this now.

**Comment by k8soneill** [comment]
Added to satellite_checkin branch
